-- ============================================================
-- FAUDI DATABASE SCHEMA (Run this in Supabase SQL Editor)
-- ============================================================

-- 1. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL CHECK (category IN ('snacks', 'buns', 'chocolate', 'gift')),
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  pack_size TEXT DEFAULT '',
  mrp TEXT NOT NULL,
  image_url TEXT NOT NULL,
  badge TEXT DEFAULT '',
  badge_color TEXT DEFAULT 'bg-brand-black text-white',
  script_tag TEXT DEFAULT '',
  nut_type TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  is_coming_soon BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. SITE SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.site_settings (
  id TEXT PRIMARY KEY DEFAULT 'default',
  name TEXT DEFAULT 'FAUDI',
  tagline TEXT DEFAULT 'GOOD FOOD. BIG MOOD.',
  whatsapp_number TEXT DEFAULT '919562313752',
  phone TEXT DEFAULT '+91 9562313752',
  email TEXT DEFAULT 'faudifoods@gmail.com',
  address TEXT DEFAULT 'Kasaragod, Kerala, India - 671121',
  fssai TEXT DEFAULT 'FSSAI Lic. No. 1XXXXXXXXXXXXX',
  instagram TEXT DEFAULT 'https://instagram.com/faudi.bites',
  facebook TEXT DEFAULT 'https://facebook.com/faudifood',
  marquee_snacks TEXT DEFAULT 'FAUDI FOODS ★ CRUNCH HARDER ★ KASARAGOD SNACKS ★ OBSESSIVELY CRAFTED ★ GOOD FOOD. BIG MOOD. ★',
  marquee_buns TEXT DEFAULT 'BUN. FILLED. DONE. ★ PILLOWY BRIOCHE ★ PISTACHIO KUNAFA ★ CHOCOLATE HAZELNUT ★ FRESH CHILLED DROPS ★',
  marquee_chocolate TEXT DEFAULT 'NUTS ABOUT CHOCOLATE ★ HEAVYWEIGHT DARK BARS ★ WHOLE ROASTED NUTS ★ MADE TO SHARE ★ MADE TO GIFT ★',
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. WHOLESALE & RETAILER INQUIRIES TABLE
CREATE TABLE IF NOT EXISTS public.inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  city TEXT NOT NULL,
  message TEXT DEFAULT '',
  status TEXT DEFAULT 'new',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- Products: Everyone can read active products, authenticated users can do everything
CREATE POLICY "Public can view active products" ON public.products
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert products" ON public.products
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update products" ON public.products
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete products" ON public.products
  FOR DELETE USING (auth.role() = 'authenticated');

-- Site Settings: Everyone can read, authenticated users can update
CREATE POLICY "Public can view site settings" ON public.site_settings
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can update site settings" ON public.site_settings
  FOR ALL USING (auth.role() = 'authenticated');

-- Inquiries: Public can insert their contact form, authenticated users can view/manage
CREATE POLICY "Public can submit inquiries" ON public.inquiries
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Authenticated users can view and manage inquiries" ON public.inquiries
  FOR ALL USING (auth.role() = 'authenticated');

-- ============================================================
-- INITIAL SEED DATA
-- ============================================================

-- Seed Site Settings
INSERT INTO public.site_settings (id, name, tagline, whatsapp_number, phone, email, address, fssai, instagram, facebook)
VALUES (
  'default',
  'FAUDI',
  'GOOD FOOD. BIG MOOD.',
  '919562313752',
  '+91 9562313752',
  'faudifoods@gmail.com',
  'Kasaragod, Kerala, India - 671121',
  'FSSAI Lic. No. 1XXXXXXXXXXXXX',
  'https://instagram.com/faudi.bites',
  'https://facebook.com/faudifood'
) ON CONFLICT (id) DO UPDATE SET
  whatsapp_number = EXCLUDED.whatsapp_number,
  email = EXCLUDED.email,
  instagram = EXCLUDED.instagram;

-- Seed Products: Kasaragod Snacks
INSERT INTO public.products (id, category, name, description, pack_size, mrp, image_url, badge, badge_color, is_coming_soon, sort_order)
VALUES
  ('soratta', 'snacks', 'Soratta', 'Traditional Kasaragod spiral crunchy rings, dusted with spicy savoury seasoning.', '200g Pack', '₹65', '/images/snacks/soratta.jpg', 'KASARAGOD ICON', 'bg-red-500 text-white', false, 10),
  ('dalda-cake', 'snacks', 'Dalda Cake', 'Old-school bakery-style soft, aromatic golden tea cake slice with caramelized edges.', '250g Box', '₹95', '/images/snacks/dalda-cake.jpg', 'FRESH BATCH', 'bg-amber-400 text-black', false, 20),
  ('malabar-mixture', 'snacks', 'Fiery Malabar Mixture', 'Crunchy sev, roasted peanuts, and fried curry leaves tossed in crushed red chili.', '200g Pack', '₹75', '/images/snacks/malabar-mixture.jpg', 'NEW RECIPE', 'bg-emerald-500 text-white', false, 30),
  ('banana-chips', 'snacks', 'Pepper Banana Chips', 'Wafer-thin Nendran banana crisps tossed in freshly crushed Tellicherry black pepper.', 'Coming Soon', '₹TBA', '/images/snacks/banana-chips.jpg', 'NEXT DROP', 'bg-purple-600 text-white', true, 40),
  ('cashew-crunch', 'snacks', 'Spiced Cashew Crunch', 'Whole roasted W240 cashews glazed in spicy Kasaragod red chili crunch.', 'Coming Soon', '₹TBA', '/images/snacks/cashew-crunch.jpg', 'COMING SOON', 'bg-blue-600 text-white', true, 50)
ON CONFLICT (id) DO NOTHING;

-- Seed Products: Cream Buns
INSERT INTO public.products (id, category, name, description, pack_size, mrp, image_url, badge, badge_color, script_tag, notes, sort_order)
VALUES
  ('chocolate-hazelnut', 'buns', 'Chocolate Hazelnut', 'Thick roasted Italian hazelnut cocoa cream loaded inside a golden brioche bun, finished with crushed toasted hazelnuts and powdered sugar.', 'Single Bun (140g)', '₹120', '/images/buns/chocolate-hazelnut.jpg', 'BESTSELLER', 'bg-brand-yellow text-brand-black', 'Rich Cocoa Silk', 'Made with authentic roasted hazelnut paste', 10),
  ('pistachio-kunafa', 'buns', 'Pistachio Kunafa', 'Inspired by the viral Dubai treat: decadent creamy pistachio filling blended with golden buttery toasted crunchy kunafa pastry.', 'Single Bun (140g)', '₹160', '/images/buns/pistachio-kunafa.jpg', 'VIRAL HIT', 'bg-brand-yellow text-brand-black', 'Dubai Pistachio Paste', 'Homemade pistachio paste & toasted kataifi crunch', 20),
  ('vanilla-honeycomb', 'buns', 'Whipped Madagascar Vanilla', 'Cold-infused real Madagascar vanilla bean cream whipped to cloud texture, paired with golden honeycomb crunch shards.', 'Single Bun (140g)', '₹110', '/images/buns/vanilla-cream.jpg', 'CLASSIC', 'bg-brand-yellow text-brand-black', 'Pure Bean Whipped', 'Real vanilla bean speckles in every bite', 30),
  ('speculoos-biscoff', 'buns', 'Spiced Speculoos Cookie', 'Deep caramelized Belgian spiced cookie butter cream whipped light, topped with crunchy cinnamon biscuit crumble.', 'Single Bun (140g)', '₹140', '/images/buns/speculoos-cream.jpg', 'PREMIUM', 'bg-brand-yellow text-brand-black', 'Caramelized Crumble', 'Sweet caramel spice with cookie crunch', 40)
ON CONFLICT (id) DO NOTHING;

-- Seed Products: Nut Chocolate Bars & Gift Box
INSERT INTO public.products (id, category, name, description, pack_size, mrp, image_url, badge, badge_color, nut_type, sort_order)
VALUES
  ('almond-crunch', 'chocolate', 'Whole Almond Dark Bar', 'Silky 55% dark chocolate bar studded with a dense row of golden roasted California almonds.', '85g Slab', '₹180', '/images/chocolate/nut-bars-hero.jpg', 'TOP PICK', 'bg-[#E5A93C] text-black', 'California Almonds', 10),
  ('pistachio-emerald', 'chocolate', 'Roasted Pistachio Emerald Bar', 'Rich dark cocoa base packed with vibrant toasted Iranian pistachios for salty-sweet balance.', '85g Slab', '₹220', '/images/chocolate/pistachio-bar.jpg', 'LIMITED BATCH', 'bg-[#E5A93C] text-black', 'Salted Pistachios', 20),
  ('roasted-peanut', 'chocolate', 'Golden Peanut Crunch Bar', 'Heavily loaded with slow-roasted crunchy golden peanuts embedded in creamy dark chocolate.', '85g Slab', '₹150', '/images/chocolate/peanut-bar.jpg', 'EVERYDAY CRUNCH', 'bg-[#E5A93C] text-black', 'Roasted Peanuts', 30),
  ('multi-seeds', 'chocolate', 'Multi-Seed Power Bar', 'Pumpkin seeds, sunflower kernels, and white sesame seeds clustered over dark chocolate.', '85g Slab', '₹170', '/images/chocolate/seeds-bar.jpg', 'CRUNCH BOMB', 'bg-[#E5A93C] text-black', 'Pumpkin & Sunflower Seeds', 40),
  ('fruit-and-nut', 'chocolate', 'Berry & Nut Velvet Bar', 'Tart freeze-dried cranberries and plump golden sultanas paired with roasted almond crunch.', '85g Slab', '₹190', '/images/chocolate/fruit-nut-bar.jpg', 'FRUITY VELVET', 'bg-[#E5A93C] text-black', 'Berries & Almonds', 50),
  ('nut-discs', 'chocolate', 'Nut Chocolate Medallions', 'Bite-sized thick circular milk & dark chocolate discs loaded with whole hazelnuts and almonds.', 'Box of 6 Discs (180g)', '₹240', '/images/chocolate/nut-discs.jpg', 'POPULAR SHARE', 'bg-[#E5A93C] text-black', 'Hazelnut & Almond Discs', 60),
  ('luxury-gift-box', 'gift', 'FAUDI Luxury Nut Chocolate Gift Box', 'An elegant presentation of 8 handcrafted chocolate bars featuring freeze-dried berries, whole roasted nuts, and edible gold dust. Perfect for festivals and corporate hampers.', 'Box of 8 Assorted Bars', '₹899', '/images/chocolate/gift-box.jpg', 'LUXURY GIFT EDITION', 'bg-[#E5A93C] text-black', 'Whole Roasted Luxury Slabs', 70)
ON CONFLICT (id) DO NOTHING;
